"""Event dataclasses for the trading bot backtesting framework.

Every component in the system communicates through these typed events via
the EventBus.  All events are plain dataclasses — no ORM, no async.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from enum import Enum, auto
from typing import Optional


# ---------------------------------------------------------------------------
# EventType
# ---------------------------------------------------------------------------

class EventType(Enum):
    BAR = auto()
    SIGNAL = auto()
    ORDER = auto()
    FILL = auto()
    RISK = auto()
    PORTFOLIO_UPDATE = auto()


# ---------------------------------------------------------------------------
# Serialisation helper
# ---------------------------------------------------------------------------

def _serialise_value(value):
    """Recursively convert a value to a JSON-safe type."""
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, uuid.UUID):
        return str(value)
    if isinstance(value, Enum):
        return value.name
    if isinstance(value, dict):
        return {k: _serialise_value(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_serialise_value(v) for v in value]
    return value


# ---------------------------------------------------------------------------
# BaseEvent
# ---------------------------------------------------------------------------

@dataclass
class BaseEvent:
    """Root class for all events.  Subclasses add domain-specific fields.

    ``event_type`` defaults to ``None`` here so that subclass dataclasses (which
    inherit this field and add their own defaulted fields after it) are valid
    Python dataclasses.  Every concrete subclass overrides the value in its
    ``__post_init__`` so ``None`` is never seen in practice.
    """

    event_type: Optional[EventType] = None
    timestamp: datetime = field(
        default_factory=lambda: datetime.now(tz=timezone.utc)
    )
    event_id: uuid.UUID = field(default_factory=uuid.uuid4)

    def to_dict(self) -> dict:
        """Return a plain dict with all fields serialised to JSON-safe types."""
        result = {}
        for f_name, f_value in self.__dict__.items():
            result[f_name] = _serialise_value(f_value)
        return result


# ---------------------------------------------------------------------------
# BarEvent
# ---------------------------------------------------------------------------

@dataclass
class BarEvent(BaseEvent):
    """A single OHLCV bar for a symbol."""

    symbol: str = ""
    date: date = field(default_factory=date.today)
    open: float = 0.0
    high: float = 0.0
    low: float = 0.0
    close: float = 0.0
    adj_close: float = 0.0
    volume: int = 0
    vwap: Optional[float] = None

    def __post_init__(self):
        # Ensure event_type is always correct regardless of caller
        self.event_type = EventType.BAR


# ---------------------------------------------------------------------------
# SignalEvent
# ---------------------------------------------------------------------------

@dataclass
class SignalEvent(BaseEvent):
    """A trade signal generated by a strategy.

    direction values: long | short | sell_put | sell_call |
                      buy_to_close | sell_to_close
    """

    symbol: str = ""
    direction: str = ""
    reason: str = ""
    strength: float = 0.0          # 0.0 – 1.0
    option_type: Optional[str] = None      # "call" | "put" | None
    strike: Optional[float] = None
    expiration: Optional[date] = None

    def __post_init__(self):
        self.event_type = EventType.SIGNAL


# ---------------------------------------------------------------------------
# OrderEvent
# ---------------------------------------------------------------------------

@dataclass
class OrderEvent(BaseEvent):
    """An order to be executed.

    action:     BUY | SELL | BTO | STO | BTC | STC
    order_type: market | limit | stop | stop_limit
    signal_ref: event_id string of the originating SignalEvent (optional)
    """

    symbol: str = ""
    action: str = ""
    order_type: str = "market"
    quantity: int = 0
    price: float = 0.0
    option_type: Optional[str] = None
    strike: Optional[float] = None
    expiration: Optional[date] = None
    signal_ref: Optional[str] = None   # UUID string, not a nested object

    def __post_init__(self):
        self.event_type = EventType.ORDER


# ---------------------------------------------------------------------------
# FillEvent
# ---------------------------------------------------------------------------

@dataclass
class FillEvent(BaseEvent):
    """A confirmed execution / fill.

    order_ref: event_id string of the originating OrderEvent (optional)
    """

    symbol: str = ""
    action: str = ""
    quantity: int = 0
    fill_price: float = 0.0
    commission: float = 0.0
    slippage: float = 0.0
    order_ref: Optional[str] = None   # UUID string, not a nested object

    def __post_init__(self):
        self.event_type = EventType.FILL


# ---------------------------------------------------------------------------
# RiskEvent
# ---------------------------------------------------------------------------

@dataclass
class RiskEvent(BaseEvent):
    """Emitted when a risk rule blocks a signal.

    signal_blocked_id: event_id string of the blocked SignalEvent — stored as
                       a plain string reference, not a nested object.
    """

    rule_name: str = ""
    signal_blocked_id: str = ""   # UUID string reference
    reason: str = ""

    def __post_init__(self):
        self.event_type = EventType.RISK


# ---------------------------------------------------------------------------
# PortfolioUpdateEvent
# ---------------------------------------------------------------------------

@dataclass
class PortfolioUpdateEvent(BaseEvent):
    """Snapshot of portfolio state after each bar / fill."""

    equity: float = 0.0
    cash: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    drawdown_pct: float = 0.0

    def __post_init__(self):
        self.event_type = EventType.PORTFOLIO_UPDATE
